### ISSUE TITLE
undefined method `location_s' for nil:NilClass

### ISSUE THREAD

**Issue by gentlemich** [robotdana/leftovers#24] opened 2023-03-22 18:56 UTC
Hi,
When running leftovers on my Mac OS 13 machine, I'm getting the error below.

Ruby 3.2.1
Rails 7.0.4.3

`/Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/definition_set.rb:22:in `location_s': undefined method `location_s' for nil:NilClass (NoMethodError)

      @definitions.first.location_s
                        ^^^^^^^^^^^
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/collection.rb:21:in `each'
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/collection.rb:21:in `sort_by'
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/collection.rb:21:in `leftovers'
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/collection.rb:34:in `empty?'
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/runner.rb:9:in `run'
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/cli.rb:14:in `run'
	from /Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/exe/leftovers:8:in `<top (required)>'
	from /Users/michael/.rvm/gems/ruby-3.2.1/bin/leftovers:25:in `load'
	from /Users/michael/.rvm/gems/ruby-3.2.1/bin/leftovers:25:in `<main>'
	from /Users/michael/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
	from /Users/michael/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'`

**Comment by robotdana** [comment] 2023-03-22 19:00
thank you for reporting this, are you able to provide the bit of ruby code being checked  + config that causes this? so i can write a failing test

**Comment by gentlemich** [comment] 2023-03-22 19:11
Hi @robotdana
I didn't set up a config file. Is there a way to show which code or file are being checked?

**Comment by robotdana** [comment] 2023-03-22 19:27
you make a good point, there is if the error occurs while gathering method names etc, not while preparing the output.

can you possibly modify the gem locally where the error is (you can open the gem file on your computer) and wrap the @definitions line with something like 

```
begin
  failing line
rescue
  put @definitions
raise
end
```

which would help me know if the issue is this definition set being empty or just containing a nil as the first item

also if you find this file in your installed gems: `https://github.com/robotdana/leftovers/blob/main/lib/leftovers/processors/each_for_definition_set.rb ` and add some logging of the contents of the variables there to find out what initial method nodes are causing the set to be empty if the set does turn out to be empty. (this is probably where i’ll end up fixing this)

when you’re done, run `gem pristine leftovers` and it’ll get rid of any hacky logging bits

**Comment by gentlemich** [comment] 2023-03-23 19:20
It seems that @definitions is nil

`/Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/definition_set.rb:22:in location_s: undefined method location_s for nil:NilClass (NoMethodError)
@definitions.first.location_s
                        ^^^^^^^^^^^`

I tried using the safe operator & but then I'm getting this:

`/Users/michael/.rvm/gems/ruby-3.2.1/gems/leftovers-0.12.1/lib/leftovers/collection.rb:21:in sort_by: comparison of NilClass with String failed (ArgumentError)
          .sort_by(&:location_s).freeze
                   ^^^^^^^^^^^^`

**Comment by robotdana** [comment] 2023-03-24 00:54
Oh, i didn't mean to close this yet. can you confirm if 0.12.2 which i've just released fixes this issue?

**Closed as completed** 2023-06-27 15:16 UTC
